---

# Ansible playbook to setup a Linux audio production system
# Draft. Prototype. Untested.
# Requires Debian 9 Stretch (testing)
# https://github.com/nodiscc/awesome-linuxaudio
# Minimum version: ansible 2.1

-

  hosts: all
  become: true
  become_user: root
  
  vars:
    #CPU scaling governor on battery mode (performance/ondemand)
    batt_cpu_governor: performance
  
  tasks:
    - name: install base packages
      apt: state=latest name={{ item }}
      with_items:
        - apt-transport-https
        - software-properties-common
        - wget
        - cpufrequtils
        - laptop-mode-tools
    
    - name: download/install kxstudio sources.list/base package
      apt: deb=https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_9.4.1~kxstudio1_all.deb
    
    - name: install gcc5 (debian 9+/ubuntu 15.10+)
      apt: name=libglibmm-2.4-1v5 state=latest
      
    - name: download/install gcc5 package from kxstudio (debian 9+/ubuntu 15.10+)
      apt: deb=https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos-gcc5_9.4.1~kxstudio1_all.deb
    
    - name: configure laptop-mode-tools (cpufreq)
      template: src=etc_laptop-mode_conf.d_board-specific_cpufreq.conf.j2
                dest=/etc/laptop-mode/conf.d/board-specific/cpufreq.conf
    
    # TODO: configure laptop-mode tools drives/USB power management
    # Another option is to create a systemd service/unit to switch governor to performance, but laptop-mode-tools has momre features
    # TODO: make kxstudio package version configurable as it will change
    # TODO: rtirq config? https://bitbucket.org/thismaechler/ubuntustudio-14.04-realtimeaudio/src/master/cfg/rtirq
    #                     http://subversion.ffado.org/wiki/IrqPriorities
    #                     http://alsa.opensrc.org/Rtirq
    # TODO: create a systemd service that further optimizes resource usage (stop radio/networking/cups/...)
    # TODO: install rt-preempt kernel, may need to reboot
    # TODO: config/optimize jack http://wiki.linuxaudio.org/wiki/list_of_jack_frame_period_settings_ideal_for_usb_interface
    #                             http://wiki.linuxaudio.org/wiki/optimize_jack
    # TODO: tweak PCI latencies? https://www.mythtv.org/wiki/PCI_Latency
    # TODO: switch CPU scheduler to BFS? https://en.wikipedia.org/wiki/Brain_Fuck_Scheduler
    # TODO: customize CPU affinity? https://www.cyberciti.biz/tips/setting-processor-affinity-certain-task-or-process.html

    - name: download realtimeconfigquickscan
      become: false
      git: repo=https://github.com/raboof/realtimeconfigquickscan dest=/tmp/realtimeconfigquickscan

    - name: run realtimeconfigquickscan
      become: false
      commmand: perl ./realTimeConfigQuickScan.pl chdir=/tmp/realtimeconfigquickscan
    
# Doc: https://bitbucket.org/thismaechler/ubuntustudio-14.04-realtimeaudio
# Doc: http://kxstudio.linuxaudio.org/Repositories
# Doc: https://github.com/raboof/realtimeconfigquickscan
# Doc: https://github.com/nodiscc/scriptz/blob/master/SNIPPETS.md